<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Aspire.RabbitMQ.Client" Version="9.5.2" />
  </ItemGroup>
	
  <ItemGroup>
	<ProjectReference Include="..\RealEstateAgency.Application.Contracts\RealEstateAgency.Application.Contracts.csproj" />
	<ProjectReference Include="..\RealEstateAgency.Generator.RabbitMq.Host\RealEstateAgency.Generator.RabbitMq.Host.csproj" />
  </ItemGroup>
</Project>
