name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./RealEstateAgency/RealEstateAgency.sln

      - name: Build
        run: dotnet build ./RealEstateAgency/RealEstateAgency --no-restore

      - name: Run tests
        run: dotnet test ./RealEstateAgency/RealEstateAgency.Tests/RealEstateAgency.Tests.csproj --no-build --verbosity normal