name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup UTF-8 locale (ru_RU.UTF-8)
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ru_RU.UTF-8
          sudo update-locale LANG=ru_RU.UTF-8
          echo "LANG=ru_RU.UTF-8" >> $GITHUB_ENV

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: dotnet restore
        run: dotnet restore ./RealEstateAgency/RealEstateAgency.sln

      - name: Build solution
        run: dotnet build ./RealEstateAgency/RealEstateAgency.sln --no-restore

      - name: Run tests
        run: dotnet test ./RealEstateAgency/RealEstateAgency.Tests/RealEstateAgency.Tests.csproj --no-build --verbosity detailed
